repos:
  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-quotes
  - repo: https://github.com/hhatto/autopep8
    rev: v2.3.1
    hooks:
      - id: autopep8
  - repo: https://github.com/aws-cloudformation/cfn-lint
    rev: v1.10.3
    hooks:
      - id: cfn-python-lint
        files: cloudformation/.*\.(json|yml|yaml)$
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=570']
  - repo: https://github.com/detailyang/pre-commit-shell
    rev: 1.0.5
    hooks:
      - id: shell-lint
        # The "-e" option excludes specific shellcheck warnings.
        # SC2028: Suggestion to use printf rather than echo.
        # SC2129: Style issue.
        args:
          - -e
          - SC2028,SC2129
  - repo: https://github.com/kynan/nbstripout
    rev: 0.7.1
    hooks:
      - id: nbstripout