name: CI

on:
  pull_request:
  push:
    branches:
      - main
      - master

permissions:
  contents: read
  pull-requests: read

jobs:
  run-pre-commit:
    name: Run pre-commit hooks
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pre-commit environment
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: >-
            pre-commit-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-
            ${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            pre-commit-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-
            pre-commit-${{ runner.os }}-

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Fetch base branch
        if: github.event_name == 'pull_request'
        run: git fetch origin "${{ github.base_ref }}"

      - name: Run pre-commit hooks
        id: run-pre-commit
        env:
          BASE_REF: ${{ github.base_ref }}
          EVENT_NAME: ${{ github.event_name }}
        run: |
          set -euo pipefail
          status=0
          if [ "${EVENT_NAME}" = "pull_request" ] && [ -n "${BASE_REF}" ]; then
            pre-commit run --from-ref "origin/${BASE_REF}" --to-ref HEAD --show-diff-on-failure --color always || status=$?
          else
            pre-commit run --all-files --show-diff-on-failure --color always || status=$?
          fi
          echo "status=${status}" >> "$GITHUB_OUTPUT"
          exit 0

      - name: Report pre-commit failures
        if: steps.run-pre-commit.outputs.status != '0'
        run: |
          echo "::error::pre-commit hooks failed. Run 'pre-commit run --all-files' locally, review the fixes, and commit the changes."
          echo "\nChanged files:" && git status --short || true
          echo "\nDiff:" && git --no-pager diff || true
          exit 1
  unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    needs: run-pre-commit

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pytest boto3 sagemaker
          pip install -e .

      - name: Run pytest
        run: pytest tests/test_pipelines.py --maxfail=1 --disable-warnings -q

  integration-tests:
    name: Run integration tests
    runs-on: ubuntu-latest
    needs: unit-tests
    if: vars.RUN_INTEGRATION_TESTS == 'true'

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION || 'eu-west-1' }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
          # Force upgrade sagemaker to absolute latest
          pip install --upgrade --force-reinstall sagemaker
          pip install -e .

      - name: Run integration tests
        run: pytest tests/integration.py --maxfail=1 --disable-warnings -q

